//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRWebApp.pg {
    
    
    public partial class dashboardStaffAnketPrint {
        
        /// <summary>
        /// dashboardStaffAnketPrintRDNO1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintRDNO1;
        
        /// <summary>
        /// dashboardStaffAnketPrintRDNO2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintRDNO2;
        
        /// <summary>
        /// dashboardStaffAnketPrintRDNO3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintRDNO3;
        
        /// <summary>
        /// dashboardStaffAnketPrintRDNO4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintRDNO4;
        
        /// <summary>
        /// dashboardStaffAnketPrintRDNO5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintRDNO5;
        
        /// <summary>
        /// dashboardStaffAnketPrintRDNO6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintRDNO6;
        
        /// <summary>
        /// dashboardStaffAnketPrintRDNO7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintRDNO7;
        
        /// <summary>
        /// dashboardStaffAnketPrintRDNO8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintRDNO8;
        
        /// <summary>
        /// dashboardStaffAnketPrintRDNO9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintRDNO9;
        
        /// <summary>
        /// dashboardStaffAnketPrintRDNO10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintRDNO10;
        
        /// <summary>
        /// dashboardStaffAnketPrintCITNO1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintCITNO1;
        
        /// <summary>
        /// dashboardStaffAnketPrintCITNO2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintCITNO2;
        
        /// <summary>
        /// dashboardStaffAnketPrintCITNO3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintCITNO3;
        
        /// <summary>
        /// dashboardStaffAnketPrintCITNO4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintCITNO4;
        
        /// <summary>
        /// dashboardStaffAnketPrintCITNO5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintCITNO5;
        
        /// <summary>
        /// dashboardStaffAnketPrintCITNO6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintCITNO6;
        
        /// <summary>
        /// dashboardStaffAnketPrintCITNO7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintCITNO7;
        
        /// <summary>
        /// dashboardStaffAnketPrintCITNO8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintCITNO8;
        
        /// <summary>
        /// dashboardStaffAnketPrintCITNO9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintCITNO9;
        
        /// <summary>
        /// dashboardStaffAnketPrintSOCNO1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintSOCNO1;
        
        /// <summary>
        /// dashboardStaffAnketPrintSOCNO2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintSOCNO2;
        
        /// <summary>
        /// dashboardStaffAnketPrintSOCNO3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintSOCNO3;
        
        /// <summary>
        /// dashboardStaffAnketPrintSOCNO4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintSOCNO4;
        
        /// <summary>
        /// dashboardStaffAnketPrintSOCNO5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintSOCNO5;
        
        /// <summary>
        /// dashboardStaffAnketPrintSOCNO6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintSOCNO6;
        
        /// <summary>
        /// dashboardStaffAnketPrintHEALNO1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintHEALNO1;
        
        /// <summary>
        /// dashboardStaffAnketPrintHEALNO2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintHEALNO2;
        
        /// <summary>
        /// dashboardStaffAnketPrintHEALNO3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintHEALNO3;
        
        /// <summary>
        /// dashboardStaffAnketPrintHEALNO4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintHEALNO4;
        
        /// <summary>
        /// dashboardStaffAnketPrintHEALNO5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintHEALNO5;
        
        /// <summary>
        /// dashboardStaffAnketPrintHEALNO6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintHEALNO6;
        
        /// <summary>
        /// dashboardStaffAnketPrintHEALNO7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintHEALNO7;
        
        /// <summary>
        /// dashboardStaffAnketPrintHEALNO8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketPrintHEALNO8;
        
        /// <summary>
        /// dashboardStaffAnketPrintLName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintLName;
        
        /// <summary>
        /// dashboardStaffAnketPrintFName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintFName;
        
        /// <summary>
        /// dashboardStaffAnketPrintImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage dashboardStaffAnketPrintImage;
        
        /// <summary>
        /// dashboardStaffAnketPrintGender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintGender;
        
        /// <summary>
        /// dashboardStaffAnketPrintBYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintBYear;
        
        /// <summary>
        /// dashboardStaffAnketPrintBMonth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintBMonth;
        
        /// <summary>
        /// dashboardStaffAnketPrintBday control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintBday;
        
        /// <summary>
        /// dashboardStaffAnketPrintBCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintBCity;
        
        /// <summary>
        /// dashboardStaffAnketPrintBDist control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintBDist;
        
        /// <summary>
        /// dashboardStaffAnketPrintBPlace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintBPlace;
        
        /// <summary>
        /// dashboardStaffAnketPrintMName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintMName;
        
        /// <summary>
        /// dashboardStaffAnketPrintNat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintNat;
        
        /// <summary>
        /// dashboardStaffAnketPrintSoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintSoc;
        
        /// <summary>
        /// dashboardStaffAnketFamily1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketFamily1;
        
        /// <summary>
        /// dashboardStaffAnketFamily2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketFamily2;
        
        /// <summary>
        /// dashboardStaffAnketPrintAddrCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintAddrCity;
        
        /// <summary>
        /// dashboardStaffAnketPrintAddrDist control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintAddrDist;
        
        /// <summary>
        /// dashboardStaffAnketPrintAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintAddress;
        
        /// <summary>
        /// dashboardStaffAnketPrintTel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintTel;
        
        /// <summary>
        /// dashboardStaffAnketPrintFax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintFax;
        
        /// <summary>
        /// dashboardStaffAnketPrintEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintEmail;
        
        /// <summary>
        /// dashboardStaffAnketPrintPostAddr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintPostAddr;
        
        /// <summary>
        /// dashboardStaffAnketPrintRelName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintRelName;
        
        /// <summary>
        /// dashboardStaffAnketPrintRelTel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPrintRelTel;
        
        /// <summary>
        /// dashboardStaffAnketEducationTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketEducationTable;
        
        /// <summary>
        /// dashboardStaffAnketPhdTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPhdTable;
        
        /// <summary>
        /// dashboardStaffAnketPhdDesc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketPhdDesc;
        
        /// <summary>
        /// dashboardStaffAnketScdDesc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketScdDesc;
        
        /// <summary>
        /// dashboardStaffAnketTrainingTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketTrainingTable;
        
        /// <summary>
        /// dashboardStaffAnketJobtitledegreeTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketJobtitledegreeTable;
        
        /// <summary>
        /// dashboardStaffAnketSciencedegreeTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSciencedegreeTable;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD1;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD22 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD22;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD2;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD23 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD23;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD3;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD24 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketSkillsD24;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD4;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD5;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD25 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD25;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD6;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD26 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD26;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD7;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD27 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD27;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD8;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD28 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD28;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD9;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD29 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD29;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD30 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD30;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD10;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD11;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD12;
        
        /// <summary>
        /// dashboardStaffAnketAnotherSkillsD1Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketAnotherSkillsD1Name;
        
        /// <summary>
        /// dashboardStaffAnketAnotherSkillsD1Val control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketAnotherSkillsD1Val;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD13;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD14;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD15;
        
        /// <summary>
        /// dashboardStaffAnketAnotherSkillsD2Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketAnotherSkillsD2Name;
        
        /// <summary>
        /// dashboardStaffAnketAnotherSkillsD2Val control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketAnotherSkillsD2Val;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD16 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD16;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD17 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD17;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD18 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD18;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD19 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD19;
        
        /// <summary>
        /// dashboardStaffAnketAnotherSkillsD3Name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketAnotherSkillsD3Name;
        
        /// <summary>
        /// dashboardStaffAnketAnotherSkillsD3Val control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketAnotherSkillsD3Val;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD20 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD20;
        
        /// <summary>
        /// dashboardStaffAnketSkillsD21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSkillsD21;
        
        /// <summary>
        /// dashboardStaffAnketLanguageskillTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketLanguageskillTable;
        
        /// <summary>
        /// dashboardStaffAnketSoftwareTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketSoftwareTable;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD1T3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD1T3;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD1T2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD1T2;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD1T1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD1T1;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD2T3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD2T3;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD2T2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD2T2;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD2T1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD2T1;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD3T3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD3T3;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD3T2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD3T2;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD3T1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD3T1;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD4T3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD4T3;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD4T2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD4T2;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD4T1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD4T1;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD5T3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD5T3;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD5T2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD5T2;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD5T1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD5T1;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD6T3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD6T3;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD6T2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD6T2;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD6T1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD6T1;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD7T3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD7T3;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD7T2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD7T2;
        
        /// <summary>
        /// dashboardStaffAnketOfficeD7T1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell dashboardStaffAnketOfficeD7T1;
        
        /// <summary>
        /// dashboardStaffAnketExphistoryTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dashboardStaffAnketExphistoryTable;
    }
}
