//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRWebApp.pg.profileforms {
    
    
    public partial class ptab1t9 {
        
        /// <summary>
        /// pTab1T9Section1ModalSelectImpltype control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T9Section1ModalSelectImpltype;
        
        /// <summary>
        /// pTab1T9Section2ModalSelectCountry control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T9Section2ModalSelectCountry;
        
        /// <summary>
        /// pTab1T9Section3ModalSelectConditiontype control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T9Section3ModalSelectConditiontype;
        
        /// <summary>
        /// pTab1T9Section3ModalSelectYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T9Section3ModalSelectYear;
        
        /// <summary>
        /// pTab1T9Section4ModalSelectCause control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T9Section4ModalSelectCause;
        
        /// <summary>
        /// pTab1T9Section4ModalSelectDecide control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T9Section4ModalSelectDecide;
    }
}
