//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRWebApp.pg.profileforms {
    
    
    public partial class ptab1t7 {
        
        /// <summary>
        /// pTab1T7Section1ModalSelectLanguage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T7Section1ModalSelectLanguage;
        
        /// <summary>
        /// pTab1T7Section1ModalSelectListenGrade control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T7Section1ModalSelectListenGrade;
        
        /// <summary>
        /// pTab1T7Section1ModalSelectSpeakGrade control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T7Section1ModalSelectSpeakGrade;
        
        /// <summary>
        /// pTab1T7Section1ModalSelectReadGrade control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T7Section1ModalSelectReadGrade;
        
        /// <summary>
        /// pTab1T7Section1ModalSelectWriteGrade control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T7Section1ModalSelectWriteGrade;
        
        /// <summary>
        /// pTab1T7Section2ModalSelectSoftware control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T7Section2ModalSelectSoftware;
        
        /// <summary>
        /// pTab1T7Section2ModalSelectGrade control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T7Section2ModalSelectGrade;
        
        /// <summary>
        /// pTab1T7Section3ModalSelectOffice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T7Section3ModalSelectOffice;
        
        /// <summary>
        /// pTab1T7Section3ModalSelectGrade control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect pTab1T7Section3ModalSelectGrade;
    }
}
